### ISSUE TITLE
Should the root of the style guide show atoms only?

### ISSUE THREAD

**Issue by beneverard** [theideabureau/style-guide-core#19]
It's helpful to see all atoms on the same page, but I don't think you need to see the other areas at this stage.

Thoughts?

**Comment by shanegriffiths** [comment]
Yeah I can get onboard with this


On 3 July 2015 at 11:03:50, Ben Everard (notifications@github.com) wrote:

It's helpful to see all atoms on the same page, but I don't think you need to see the other areas at this stage.

Thoughts?

**Comment by beneverard** [comment]
Just implemented, works well, keeps things a bit leaner.
